name: zhitrend_nas_app
description: A mobile app for ZhiTrend NAS
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^4.0.2
  flutter_local_notifications: ^15.1.0+1
  permission_handler: ^10.4.3
  file_picker: ^5.5.0
  share_plus: ^7.2.1
  http: ^1.1.0
  photo_view: ^0.14.0
  google_fonts: ^5.1.0
  synchronized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
