name: zhitrend_nas_app
description: A mobile app for ZhiTrend NAS
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^4.0.2
  flutter_local_notifications: ^15.1.0+1
  permission_handler: ^10.4.3
  file_picker: ^5.5.0
  share_plus: ^7.2.1
  http: ^1.1.0
  photo_view: ^0.14.0
  google_fonts: ^5.1.0
  synchronized: ^3.1.0
  
  # 预览增强
  video_player: ^2.7.0
  chewie: ^1.7.0
  flutter_pdfview: ^1.3.1
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.34
  open_file: ^3.3.2
  syncfusion_flutter_pdfviewer: ^22.1.34  # 替换 office_viewer
  image_editor: ^1.3.0
  
  # 同步备份
  photo_manager: ^2.7.0
  background_fetch: ^1.2.1
  workmanager: ^0.5.1
  path_provider: ^2.1.1
  crypto: ^3.0.3
  queue: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Medium.ttf
    - assets/fonts/Roboto-Bold.ttf
